# -*- coding: utf-8 -*-
"""Unstructured_V2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D7F86j8UZuxok0PspnbavAW-74KZRCe4
"""

# Use Unstructured to parse the PDF. While unstructured has a core library for processing PDFs, HTML etc, they use
# another library, unstructured_inference, for PDFs with Tables.
# Unstructured_inference uses the YOLOX ML model to parse the PDF. PDF libraries like PDFMiner, Camelot etc are not used.
# However, YOLOX has challenges with complex Tables. Specifically, we seem to get many unnecessary "UncategorizedText" elements.
# Almost like a Table got blown up.
# This code REPLACES YOLO's Tables with Tables from Tabula (in a DataFrame Format) and also eliminates the spurious
# UncategorizedTexts.
# So it can be considered as a hybrid approach using a ML Model & conventional coding.
# While "Chunking By Title" comes out-of-the-box with unstructured-core, there are some challenges in converting objects from
# unstructured_inference to the unstructured-core model, hence using a Custom Chunk By Title approach.
# Trying to get help from unstructured community on the above.
# ToDo - Merge Tables spanning multiple Pages
